---
  - name: Copy linux mint timer service for ISO
    ansible.builtin.copy:
      src:  SO/confd/mintUpdateSO.timer
      dest: /etc/systemd/system/mintUpdateSO.timer
      owner: root
      group: root
      mode: '0644'

  - name: Copy linux mint service for ISO
    ansible.builtin.copy:
      src: SO/confd/mintUpdateSO.service
      dest: /etc/systemd/system/mintUpdateSO.service
      owner: root
      group: root
      mode: '0644'
  
  - name: Copy linux mint action files for ISO
    ansible.builtin.copy:
      src:  SO/confd/scripts/mintfetchSO.sh
      dest: /usr/local/bin/mintfetchSO.sh
      owner: root
      group: root
      mode: '0755'

  - name: Copy linux mint timer service for RP
    ansible.builtin.copy:
      src: repository/confd/mintUpdateRP.timer
      dest: /etc/systemd/system/mintUpdateRP.timer
      owner: root
      group: root
      mode: '0644'

  - name: Copy linux mint service for RP
    ansible.builtin.copy:
      src:  repository/confd/mintUpdateRP.service
      dest: /etc/systemd/system/mintUpdateRP.service
      owner: root
      group: root
      mode: '0644'
  
  - name: Copy linux mint action files for RP
    ansible.builtin.copy:
      src:  repository/confd/scripts/mintfetchRP.sh
      dest: /usr/local/bin/mintfetchRP.sh
      owner: root
      group: root
      mode: '0755'

  - name: Start timer service for ISO
    ansible.builtin.systemd_service:
      name: mintUpdateSO.timer
      enabled: true
      state: started
      daemon_reload: true

  - name: Start timer service for RP
    ansible.builtin.systemd_service:
      name: mintUpdateRP.timer
      enabled: true
      state: started
      daemon_reload: true
...