- name: Ansible playbook that automates router configuration
  hosts: routers
  become: true

  roles:
    - secure_conf # Apply basic configuration
    - vpn # VPN configuration
    - router # Router configuration

  handlers:
    - name: Apply sysctl configuration
      ansible.builtin.command:
        cmd: sysctl --system
