- name: Ansible playbook that automates router configuration
  hosts: routers
  become: true

  tasks:
    # Apply basic configuration
    - ansible.builtin.import_tasks: tasks/unattended-upgrades.yml
    - ansible.builtin.import_tasks: tasks/sshd.yml

    # Configure netplan
    - name: Copy armbian.yaml file
      ansible.builtin.copy:
        src: files/armbian.yaml
        dest: /etc/netplan/armbian.yaml
        mode: '0644'
        owner: root
        group: root
      notify:
        - Apply netplan configuration

    # Configure dnsmasq
    - name: Ensure that dnsmasq is installed
      ansible.builtin.apt:
        name: dnsmasq
        state: present
        update_cache: yes
    - name: Copy lan.conf file
      ansible.builtin.copy:
        src: files/lan.conf
        dest: /etc/dnsmasq.d/lan.conf
        mode: '0644'
        owner: root
        group: root
      notify:
        - Restart dnsmasq

    # Configure nftables
    - name: Ensure that nftables is installed
      ansible.builtin.apt:
        name: nftables
        state: present
        update_cache: yes
    - name: Copy nftables.conf file
      ansible.builtin.copy:
        src: files/nftables.conf
        dest: /etc/nftables.conf
        mode: '0644'
        owner: root
        group: root
      notify:
        - Restart nftables
    - name: Create systemd override directory for nftables
      ansible.builtin.file:
        path: /etc/systemd/system/nftables.service.d
        state: directory
        mode: '0755'
        owner: root
        group: root
    - name: Copy nftables systemd override
      ansible.builtin.copy:
        src: files/nftables-override.conf
        dest: /etc/systemd/system/nftables.service.d/override.conf
        mode: '0644'
        owner: root
        group: root
      notify:
        - Reload systemd
        - Restart nftables

    # Configure ip forwarding
    - name: Copy 99-router.conf file
      ansible.builtin.copy:
        src: files/99-router.conf
        dest: /etc/sysctl.d/99-router.conf
        mode: '0644'
        owner: root
        group: root
      notify:
        - Apply sysctl configuration

    # Configure WireGuard
    - name: Ensure that wireguard-tools is installed
      ansible.builtin.apt:
        name: wireguard-tools
        state: present
        update_cache: yes
    - name: Create wireguard directory
      ansible.builtin.file:
        path: /etc/wireguard
        state: directory
        mode: '0700'
        owner: root
        group: root
    - name: Copy wg0.conf file
      ansible.builtin.copy:
        src: files/wg0.conf
        dest: /etc/wireguard/wg0.conf
        mode: '0600'
        owner: root
        group: root
      notify:
        - Restart wireguard
        - Restart nftables

    # Ensure services are enabled
    - name: Ensure dnsmasq service is enabled
      ansible.builtin.service:
        name: dnsmasq.service
        enabled: true
    - name: Ensure nftables service is enabled
      ansible.builtin.service:
        name: nftables.service
        enabled: true
    - name: Ensure wireguard service is enabled
      ansible.builtin.service:
        name: wg-quick@wg0.service
        enabled: true

  handlers:
    - name: Apply netplan configuration
      ansible.builtin.command:
        cmd: netplan apply

    - name: Restart dnsmasq
      ansible.builtin.service:
        name: dnsmasq.service
        state: restarted

    - name: Restart wireguard
      ansible.builtin.service:
        name: wg-quick@wg0.service
        state: restarted

    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Restart nftables
      ansible.builtin.service:
        name: nftables.service
        state: restarted

    - name: Apply sysctl configuration
      ansible.builtin.command:
        cmd: sysctl --system
