# /etc/netplan/armbian.yaml

network:
  version: 2
  renderer: networkd
  ethernets:
    wan:
      addresses:
      - "132.248.59.72/24"
      nameservers:
        addresses:
        - 9.9.9.9
        - 1.1.1.1
      dhcp4: false
      dhcp6: false
      macaddress: "ee:5d:d7:97:2e:14"
      routes:
      - metric: 200
        to: "0.0.0.0/0"
        via: "132.248.59.254"
    lan: {}
  bridges:
    br0:
      interfaces:
      - lan
      dhcp4: false
      addresses:
      - "10.8.24.1/24"
