#
# quick-fedora-mirror installation
#
- name: Clone quick-fedora-mirror from the official repository
  ansible.builtin.git:
    repo: 'https://pagure.io/quick-fedora-mirror.git'
    dest: /opt/fedora-mirror

- name: Copy configuration file
  ansible.builtin.copy:
    src: quick-fedora-mirror.conf
    dest: /etc/quick-fedora-mirror.conf
    mode: '0644'
    owner: root
    group: root
  notify: Reload service and timer

#
# Timer configuration for periodic sync
#

- name: Copy fedora-mirror service
  ansible.builtin.copy:
    src: fedora-mirror.service
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: '0644'
  notify: Reload service and timer

- name: Copy fedora-mirror timer
  ansible.builtin.copy:
    src: fedora-mirror.timer
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: '0644'
  notify: Reload service and timer
