apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: gitops-apps-updater
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  writeBackConfig:
    method: argocd
  applicationRefs:
    - namePattern: "*"
      images:
        - alias: mariadb
          imageName: docker.io/library/mariadb:11
          commonUpdateSettings:
            updateStrategy: semver
          manifestTargets:
            kustomize:
              name: docker.io/library/mariadb
        - alias: nextcloud
          imageName: docker.io/library/nextcloud:33
          commonUpdateSettings:
            updateStrategy: semver
          manifestTargets:
            kustomize:
              name: docker.io/library/nextcloud
        - alias: redis
          imageName: docker.io/library/redis:7-alpine
          commonUpdateSettings:
            updateStrategy: semver
          manifestTargets:
            kustomize:
              name: docker.io/library/redis
        - alias: website
          imageName: ghcr.io/lidsol/sitio-web-lidsol:master
          commonUpdateSettings:
            updateStrategy: digest
          manifestTargets:
            kustomize:
              name: ghcr.io/lidsol/sitio-web-lidsol
        - alias: drawdb
          imageName: ghcr.io/lidsol/drawdb:main
          commonUpdateSettings:
            updateStrategy: digest
          manifestTargets:
            kustomize:
              name: ghcr.io/lidsol/drawdb
        - alias: speedtest
          imageName: lscr.io/linuxserver/speedtest-tracker:latest
          commonUpdateSettings:
            updateStrategy: digest
          manifestTargets:
            kustomize:
              name: lscr.io/linuxserver/speedtest-tracker